### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by eastpeak** [tdreyno/middleman-blog-editor-issues#4]
I installed blog editor successfully and get this error when previewing with middleman server. 

== The Middleman is standing watch at http://0.0.0.0:4567
NoMethodError: undefined method `blog' for #<Middleman::Application:0x23983068>
        C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/middleman-blog-editor-0.4.0/lib/middleman-blog-editor
/extension.rb:84:in`call'
        C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rack-1.4.5/lib/rack/showexceptions.rb:24:in `call'
        C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:134:in`call'
        C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rack-1.4.5/lib/rack/handler/webrick.rb:59:in `service
'
        C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
        C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
        C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'

**Comment by eastpeak** [comment]
Solved by adding activate :blog before activate :blog_editor in config.rb
